name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:

  build_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Remove Git folders from distribution
        run: rm -rf .git*
      - name: Install Dependencies
        run: npm install --prefix functions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v12.9.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
